const C=SaihCore,R=SaihRemote,ONLINE=R.enabled,KEY='saih-comidas-demo-v1';
let data,storageOk=true;
const selectedInvites=new Set();let batchRequest=null;
try{const saved=ONLINE?null:localStorage.getItem(KEY);data=saved?JSON.parse(saved):C.seed();if(data.version!==1||!Array.isArray(data.users)||!Array.isArray(data.events))throw Error('schema');}catch{data=C.seed();storageOk=false;}
if(ONLINE)data={version:1,users:[],events:[]};
let page='meals',role='admin',eventId=data.events[0]?.id,guestId=data.users[0]?.id,filter='all';
const app=document.getElementById('app'),modal=document.getElementById('modal');
const h=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('es-ES',{day:'numeric',month:'long',year:'numeric'}):'Fecha por decidir';
const current=()=>data.events.find(e=>e.id===eventId);
let indexedUsers,usersById;
const user=id=>{if(indexedUsers!==data.users){indexedUsers=data.users;usersById=new Map(data.users.map(u=>[u.id,u]));}return usersById.get(id);};
const icon=(kind)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true">${({meals:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m0-17a3 3 0 0 1 0 6m3 5a5 5 0 0 1 3 5"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 4 3v2m-1 3h.01"/>'})[kind]}</svg>`;
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3800);}
async function commit(fn){const next=structuredClone(data);fn(next);if(ONLINE){data=await R.apply(data,next,role);return;}try{localStorage.setItem(KEY,JSON.stringify(next));}catch{throw Error('No se pudo guardar. El navegador tiene el almacenamiento bloqueado o lleno.');}data=next;storageOk=true;}
const pill=(label,color)=>`<span class="pill ${color}">${h(label)}</span>`;
const stage=e=>pill(e.stage==='poll'?'Encuesta abierta':e.stage==='confirm'?'Confirmación abierta':'Cerrada',e.stage==='poll'?'blue':e.stage==='confirm'?'green':'gray');
const response=i=>pill({yes:'Confirmado',no:'No asiste',pending:'Pendiente'}[i.response],{yes:'green',no:'red',pending:'amber'}[i.response]);
const allergy=u=>u.allergyStatus==='none'?'Sin alergias declaradas':u.allergyStatus==='specified'?u.allergies:'Sin indicar';
const person=u=>`<div class="person"><span class="avatar">${h(u.name.split(' ').map(p=>p[0]).slice(0,2).join(''))}</span>${h(u.name)}</div>`;
const team=u=>`<span class="team ${h(u.team.toLowerCase())}">${h(u.team||'Sin equipo')}</span>`;
function render(){app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand brand-with-logo"><img class="site-logo" src="logo-saih.webp" alt="SAIH Tajo · Comidas" width="1370" height="1148"></div><nav class="nav" aria-label="Principal">${(ONLINE?(role==='guest'?[['meals','Mi invitación']]:[['meals','Comidas'],['users','Usuarios']]):[['meals','Comidas'],['users','Usuarios'],['help','Cómo probarlo']]).map(([id,label])=>`<button data-action="nav" data-id="${id}" class="${page===id?'active':''}">${icon(id)}${label}</button>`).join('')}</nav><div class="sidebar-note"><strong>Todo en un mismo lugar</strong>Comidas, respuestas y preferencias alimentarias.<br><br>${ONLINE?'Comidas y respuestas en una única base de datos.':'Demostración con usuarios ficticios.'}</div></aside><section class="content"><header class="topbar"><div class="demo"><b>${ONLINE?'EN LÍNEA':'DEMO LOCAL'}</b> ${ONLINE?'Datos sincronizados':'Solo se guarda en este navegador'}</div>${ONLINE?`<div class="inline"><button class="btn small" data-action="refresh">Actualizar</button>${role==='admin'?'<button class="btn small" data-action="logout">Salir</button>':''}</div>`:`<div class="role"><span>Probar como</span><div class="switches"><button data-action="role" data-id="admin" class="${role==='admin'?'active':''}">Organización</button><button data-action="role" data-id="guest" class="${role==='guest'?'active':''}">Invitado</button></div></div>`}</header><main class="${role==='guest'&&page==='meals'?'guest':''}">${!storageOk?'<div class="notice warn">No se han podido recuperar los datos guardados. Estás viendo datos de ejemplo.</div>':''}${page==='help'?help():role==='guest'?guest():page==='users'?users():meals()}</main></section></div>`;}
function heading(title,sub,button=''){return `<div class="page-heading"><div><p class="eyebrow">${role==='guest'?'Tu invitación':'Organización'}</p><h1>${title}</h1><p class="sub">${sub}</p></div>${button}</div>`;}
function eventSelect(){return `<div class="toolbar"><label for="event-select">Comida</label><select id="event-select" data-change="event">${data.events.map(e=>`<option value="${h(e.id)}" ${e.id===eventId?'selected':''}>${h(e.title)}</option>`).join('')}</select></div>`;}
function banner(e){return `<div class="event-banner"><div><h2>${h(e.title)}</h2><div class="meta"><span>${date(e.date)}</span>${e.time?`<span>Reserva a las ${h(e.time)} · hora de Madrid</span>`:''}<span>${h(e.place||'Lugar por decidir')}</span>${e.food?`<span>${h(e.food)}</span>`:''}${e.deadline?`<span>Hasta el ${date(e.deadline)}</span>`:''}</div><div class="inline" style="margin-top:12px">${e.mapsUrl?`<a class="btn small" href="${h(C.safeUrl(e.mapsUrl))}" target="_blank" rel="noopener noreferrer">Cómo llegar</a>`:''}${e.websiteUrl?`<a class="btn small" href="${h(C.safeUrl(e.websiteUrl))}" target="_blank" rel="noopener noreferrer">Web del restaurante</a>`:''}</div></div>${C.isExpired(e)&&e.stage!=='closed'?pill('Plazo terminado','gray'):stage(e)}</div>`;}
function meals(){const e=current();return heading('Nos vemos a la mesa','Organiza la próxima comida y sigue las respuestas.',`<button class="btn primary" data-action="new-event">＋ Nueva comida</button>`)+(!e?'<div class="empty">Crea una comida para empezar.</div>':eventSelect()+banner(e)+stats(e)+`<div class="toolbar"><button class="btn primary" data-action="add-invitees">＋ Añadir personas a esta comida</button><button class="btn" data-action="edit-event">Editar detalles</button>${ONLINE?'':'<button class="btn" data-action="invitation">Texto de invitación</button>'}<button class="btn" data-action="export">Exportar listado</button>${e.stage!=='closed'?'<button class="btn" data-action="close-event">Cerrar comida</button>':'<button class="btn" data-action="reopen">Reabrir confirmación</button>'}</div>`+(e.stage==='poll'?pollAdmin(e):'')+attendees(e));}
function stats(e){const c=C.counts(e);return `<div class="stats">${[['Invitados',c.total,''],['Confirmados',c.yes,'yes'],['No asisten',c.no,'no'],['Pendientes',c.pending,'pending'],...(e.stage==='poll'?[]:[['Acompañantes',c.companions,'yes'],['Comensales',c.yes+c.companions,'yes']])].map(([label,value,cl])=>`<div class="stat ${cl}"><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>`;}
function pollAdmin(e){const c=C.counts(e);return `<div class="split"><section class="panel"><div class="panel-head"><h2>¿Qué nos apetece comer?</h2>${pill(c.voted+' / '+c.total+' votos','blue')}</div><div class="panel-body">${e.options.map(o=>{const n=e.invitations.filter(i=>i.vote===o.id).length;return `<div class="progress-option"><div class="progress-label"><span>${h(o.label)}</span><strong>${n} ${n===1?'voto':'votos'}</strong></div><div class="track"><span style="width:${c.total?n/c.total*100:0}%"></span></div></div>`;}).join('')}<p class="muted">Una opción por persona. Pueden cambiar su voto mientras la encuesta esté abierta.</p></div></section><section class="panel"><div class="panel-head"><h2>De la encuesta a la comida</h2></div><div class="panel-body stack"><p class="muted">Cuando lo decidas, elige el tipo de comida y abre la confirmación de asistencia. Votar no confirma que se vaya a asistir.</p><label class="field">Tipo de comida elegido<select id="chosen-food">${e.options.map(o=>`<option value="${h(o.label)}">${h(o.label)}</option>`).join('')}</select></label><button class="btn primary" data-action="finish-poll">Abrir confirmación</button></div></section></div>`;}
function attendees(e){const rows=e.invitations.filter(i=>filter==='all'||i.response===filter);return `<section class="panel"><div class="panel-head"><h2>Personas invitadas</h2>${ONLINE?`<button class="btn primary" data-action="review-invites" ${selectedInvites.size?'':'disabled'}>Revisar envío (${selectedInvites.size})</button>`:''}<select aria-label="Filtrar por respuesta" data-change="filter">${[['all','Todas las respuestas'],['yes','Confirmados'],['no','No asisten'],['pending','Pendientes']].map(([id,label])=>`<option value="${id}" ${filter===id?'selected':''}>${label}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr>${ONLINE?'<th><input type="checkbox" aria-label="Seleccionar todas las personas visibles" data-change="invite-all" ' + (rows.length&&rows.every(i=>selectedInvites.has(i.userId))?'checked':'') + '></th>':''}<th>Persona</th><th>Equipo</th><th>Asistencia</th>${e.stage==='poll'?'<th>Encuesta</th>':''}<th>Alimentación · organización</th><th></th></tr></thead><tbody>${rows.map(i=>{const u=user(i.userId);return `<tr>${ONLINE?`<td><input type="checkbox" aria-label="Seleccionar a ${h(u.name)}" data-change="invite-one" data-id="${h(u.id)}" ${selectedInvites.has(u.id)?'checked':''}></td>`:''}<td>${person(u)}${(i.companions||[]).map(g=>`<small>Acompañante: ${h(g.name)}${i.response!=='yes'?' · sin confirmar':''}</small>`).join('')}</td><td>${team(u)}</td><td>${response(i)}</td>${e.stage==='poll'?`<td>${h(e.options.find(o=>o.id===i.vote)?.label||'Sin votar')}</td>`:''}<td>${h(allergy(u))}${u.preferences?`<small>Preferencias: ${h(u.preferences)}</small>`:''}${(i.companions||[]).map(g=>`<small>${h(g.name)}: ${h(g.allergies||'Sin indicar')}</small>`).join('')}</td><td><button class="btn small" data-action="${ONLINE?'personal-invite':'simulate'}" data-id="${h(u.id)}">${ONLINE?'Invitar por correo':'Probar invitación'}</button></td></tr>`;}).join('')||`<tr><td colspan="6" class="empty">No hay personas con esta respuesta.</td></tr>`}</tbody></table></div></section>`;}
function users(){return heading('Personas y preferencias','Una ficha por persona, reutilizada en todas las comidas.',`<button class="btn primary" data-action="new-user">＋ Añadir persona</button>`)+`<div class="notice" style="margin-bottom:22px">Alergias e intolerancias se registran aparte de las preferencias. Un campo vacío significa «Sin indicar», no que no haya alergias.</div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Persona</th><th>Equipo</th><th>Alergias e intolerancias</th><th>Preferencias</th><th></th></tr></thead><tbody>${data.users.map(u=>`<tr><td>${person(u)}<small>${h(u.email||'Correo sin indicar')}</small></td><td>${team(u)}</td><td>${h(allergy(u))}</td><td>${h(u.preferences||'—')}</td><td><button class="btn small" data-action="edit-user" data-id="${h(u.id)}">Editar ficha</button></td></tr>`).join('')}</tbody></table></div></section><p class="footer-note">Las nuevas comidas invitan a todas las personas de este listado. Para incluirla en una comida existente, abre esa comida y pulsa «Añadir personas a esta comida».</p>`;}
async function sendBatch(b){if(!batchRequest)return;b.disabled=true;try{const result=await R.sendInvitations(batchRequest.eventId,batchRequest.userIds,batchRequest.requestId);show('Resultado del envío',`<p>Las personas están incluidas en la comida.</p><ul>${result.results.map(r=>`<li>${h(user(r.userId)?.name||'Invitado')}: ${h(r.status==='sent'?'Enviado':R.errorMessage(r.message||'No enviado'))}</li>`).join('')}</ul><p>Enviado significa que el servicio de correo ha aceptado el mensaje.</p><div class="error" role="alert"></div>${result.results.some(r=>r.status!=='sent')?'<button class="btn primary" data-action="send-invites">Reintentar este lote</button>':''}<button class="btn" data-action="dismiss">Cerrar</button>`);selectedInvites.clear();render();}catch(error){modal.querySelector('.error').textContent=R.errorMessage(error);b.disabled=false;}}
function addInviteesForm(){const e=current();if(e.stage==='closed'||C.isExpired(e))throw Error('Reabre la comida o amplía el plazo antes de añadir personas.');const existing=new Set(e.invitations.map(i=>i.userId)),available=data.users.filter(u=>!existing.has(u.id));show('Añadir personas a esta comida',`<p><strong>${h(e.title)}</strong></p><p>Se añadirán como pendientes y se enviará un correo individual a cada persona con su enlace personal. Selecciona hasta 30 personas por envío.</p><form id="add-invitees-form" data-event="${h(e.id)}"><div class="stack" style="max-height:320px;overflow:auto">${available.map(u=>`<label class="choice"><input type="checkbox" name="invitee" value="${h(u.id)}"><span>${h(u.name)}<small style="display:block">${h(u.team)} · ${h(u.email||'Sin correo')}</small></span></label>`).join('')||'<p class="notice">Todas las personas del listado ya están incluidas en esta comida.</p>'}</div><p class="muted">Si todavía no figura en Usuarios, crea primero su ficha y vuelve a este botón.</p><button type="button" class="btn" data-action="go-users">Ir a Usuarios</button><div class="error" role="alert"></div><div class="form-actions"><button type="button" class="btn" data-action="dismiss">Cancelar</button><button class="btn primary" ${available.length?'':'disabled'}>${ONLINE?'Añadir y enviar invitaciones':'Añadir seleccionados'}</button></div></form>`);}
function companionFields(i,locked){const guests=i.companions||[];return `<fieldset id="companion-section" class="companion-section" ${i.response!=='yes'?'hidden disabled':''} ${locked?'disabled':''}><legend>¿Llevas invitados?</legend><label class="field">Acompañantes<select name="companionCount" data-change="companions" aria-controls="companion-fields"><option value="0" ${!guests.length?'selected':''}>No, voy sin invitados</option><option value="1" ${guests.length===1?'selected':''}>Sí, llevo 1 invitado</option><option value="2" ${guests.length===2?'selected':''}>Sí, llevo 2 invitados</option></select></label><div id="companion-fields">${[0,1].map(n=>`<fieldset class="companion-card" data-companion="${n}" ${n>=guests.length?'hidden disabled':''}><legend>Invitado ${n+1}</legend><label class="field">Nombre y apellidos<input name="companionName${n}" maxlength="100" value="${h(guests[n]?.name||'')}" required autocomplete="off"></label><label class="field">Alergias, intolerancias o necesidades alimentarias <small>Opcional. Si no tiene, puedes escribir «Ninguna».</small><textarea name="companionAllergies${n}" maxlength="1000">${h(guests[n]?.allergies||'')}</textarea></label></fieldset>`).join('')}</div><p class="muted">Máximo dos invitados, sin correo. Sus datos se guardan solo para esta comida y Richard podrá consultarlos.</p></fieldset>`;}
function guest(){const e=current();if(!e)return heading('Tu invitación','Todavía no hay comidas.')+'';if(!e.invitations.some(i=>i.userId===guestId))guestId=e.invitations[0]?.userId;const u=user(guestId);if(!u)return heading('Sin invitados','Añade usuarios antes de crear una comida.');const i=C.invite(e,u.id),locked=C.isExpired(e)||e.stage==='closed';return heading('Tu sitio en la mesa','Responde a la invitación y revisa tus preferencias.')+(ONLINE?'':eventSelect())+`${ONLINE?'':`<div class="guest-selector"><label for="guest-select">Vista de invitado · simulación</label><select id="guest-select" data-change="guest">${e.invitations.map(i=>`<option value="${h(i.userId)}" ${i.userId===u.id?'selected':''}>${h(user(i.userId).name)}</option>`).join('')}</select></div>`}`+banner(e)+`<section class="panel"><div class="panel-head"><h2>${e.stage==='poll'?'¿Qué te apetece comer?':'¿Te apuntas, '+h(u.name)+'?'}</h2>${e.stage!=='poll'?response(i):pill(i.vote?'Voto guardado':'Sin votar',i.vote?'green':'amber')}</div><div class="panel-body">${locked?'<div class="notice warn">El plazo está cerrado. Puedes consultar tu respuesta, pero no modificarla.</div>':''}<form id="reply-form"><div class="option-grid" style="margin-top:14px">${(e.stage==='poll'?e.options.map(o=>[o.id,o.label,i.vote===o.id]):[['yes','Sí, voy',i.response==='yes'],['no','No puedo ir',i.response==='no'],['pending','Todavía no lo sé',i.response==='pending']]).map(([id,label,checked])=>`<label class="choice"><input type="radio" name="answer" value="${h(id)}" ${checked?'checked':''} ${locked?'disabled':''} required>${h(label)}</label>`).join('')}</div>${e.stage!=='poll'?companionFields(i,locked):''}<p class="muted">${e.stage==='poll'?'Esta encuesta sirve para elegir el tipo de comida. La asistencia se confirmará después.':'Puedes cambiar tu respuesta hasta que termine el plazo.'}</p><div class="error" role="alert"></div><button class="btn primary" ${locked?'disabled':''}>${e.stage==='poll'?'Guardar voto':'Guardar respuesta'}</button></form></div></section><section class="panel"><div class="panel-head"><h2>Tu alimentación</h2>${pill('Ficha personal','gray')}</div><div class="panel-body"><p class="muted">Indica lo que necesita saber la organización. Las preferencias no se consideran alergias.</p><form id="profile-form"><div class="stack">${profileFields(u)}</div><div class="error" role="alert"></div><div class="form-actions"><button class="btn primary">Guardar mi ficha</button></div></form></div></section><p class="footer-note">${ONLINE?'Este enlace es personal. No lo reenvíes. La organización podrá consultar tus respuestas y tu ficha alimentaria.':'En esta demo puedes cambiar de persona para probar el recorrido. La versión online necesitará enlaces personales y control de acceso real.'}</p>`;}
function profileFields(u){return `<label class="field">Alergias o intolerancias<select name="allergyStatus" data-change="allergy">${[['unknown','Sin indicar'],['none','No tengo alergias ni intolerancias'],['specified','Sí, quiero detallarlas']].map(([id,label])=>`<option value="${id}" ${u.allergyStatus===id?'selected':''}>${label}</option>`).join('')}</select></label><label class="field allergy-detail" ${u.allergyStatus!=='specified'?'hidden':''}>Alimentos o ingredientes que debes evitar<textarea name="allergies" maxlength="1000" placeholder="Ej.: frutos secos, lactosa…" ${u.allergyStatus==='specified'?'required':''}>${h(u.allergies)}</textarea></label><label class="field">Otras preferencias alimentarias <small>Opcional. Por ejemplo, menú vegetariano o sin pescado.</small><textarea name="preferences" maxlength="1000">${h(u.preferences)}</textarea></label>`;}
function help(){return heading('Prueba el recorrido completo','Todo lo que cambies aquí se queda en este navegador.')+`<div class="help-grid"><section class="panel"><div class="panel-body"><h3>1. Una encuesta antes de decidir</h3><p>Abre la comida de ejemplo y cambia a Invitado. Elige una persona y guarda su voto. Vuelve a Organización para ver cómo se actualizan los resultados.</p><h3>2. Confirma la asistencia</h3><p>En Organización, elige el tipo de comida y pulsa «Abrir confirmación». Los invitados podrán confirmar, rechazar o dejar su respuesta pendiente.</p></div></section><section class="panel"><div class="panel-body"><h3>3. Una ficha para cada persona</h3><p>Prueba alergias, intolerancias y preferencias desde la vista de invitado. La organización las verá en el listado; el invitado solo ve la ficha seleccionada.</p><h3>4. Conserva las comidas anteriores</h3><p>Crea una nueva comida. Cada una conserva sus votos y respuestas. Los usuarios y sus preferencias se mantienen en una sola ficha.</p></div></section></div><div class="notice warn">Esta es una simulación local con usuarios ficticios, sin autenticación. No introduzcas información sensible real. Los enlaces personales, los correos y el acceso desde distintos dispositivos se incorporarán al conectar la base de datos online.</div><p class="muted">Si borras los datos del navegador, también se borrará esta prueba. No hay sincronización ni envío de datos a un servidor.</p><button class="btn danger" data-action="reset">Restablecer datos de prueba</button>`;}
function show(title,body){modal.innerHTML=`<header><h2>${title}</h2><button class="close" data-action="dismiss" aria-label="Cerrar">×</button></header>${body}`;modal.showModal();}
function eventForm(edit=false){const e=edit?current():null;show(edit?'Editar comida':'Nueva comida',`<form id="event-form" data-edit="${edit?'1':''}"><div class="fields"><label class="field wide">Nombre<input name="title" required maxlength="100" value="${h(e?.title||'')}" placeholder="Ej.: Comida de octubre"></label><label class="field">Fecha de la comida<input type="date" name="date" value="${h(e?.date||'')}"></label><label class="field">Hora de la reserva<input type="time" name="time" value="${h(e?.time||'')}"></label><label class="field">Último día para responder<input type="date" name="deadline" value="${h(e?.deadline||'')}"></label><label class="field wide">Lugar / restaurante<input name="place" maxlength="150" value="${h(e?.place||'')}"></label><label class="field wide">Enlace al mapa (opcional)<input type="url" name="mapsUrl" placeholder="https://maps.google.com/…" value="${h(e?.mapsUrl||'')}"></label><label class="field wide">Web del restaurante (opcional)<input type="url" name="websiteUrl" placeholder="https://…" value="${h(e?.websiteUrl||'')}"></label>${!edit?`<label class="field wide">Cómo quieres empezar<select name="stage" data-change="stage"><option value="poll">Encuesta para elegir tipo de comida</option><option value="confirm">Confirmación de asistencia</option></select></label><label class="field wide poll-options">Opciones de la encuesta <small>Una opción por línea, entre 2 y 8.</small><textarea name="options">Cocido\nArroces\nMenú vegetariano</textarea></label>`:''}<label class="field wide">Tipo de comida ${!edit?'(si ya está decidido)':''}<input name="food" maxlength="100" value="${h(e?.food||'')}"></label></div><p class="muted">${edit?'Cambiar fecha, hora o lugar devuelve las asistencias a pendientes para que cada persona confirme de nuevo.':`Se invitará a las ${data.users.length} personas del listado de usuarios.`}</p><div class="error" role="alert"></div><div class="form-actions"><button type="button" class="btn" data-action="dismiss">Cancelar</button><button class="btn primary">${edit?'Guardar cambios':'Crear comida'}</button></div></form>`);}
function userForm(id){const u=id?user(id):{name:'',email:'',team:'',allergyStatus:'unknown',allergies:'',preferences:''};show(id?'Editar ficha':'Añadir persona',`<form id="user-form" data-id="${h(id||'')}"><div class="fields"><label class="field">Nombre<input required name="name" maxlength="100" value="${h(u.name)}"></label><label class="field">Equipo<input required name="team" maxlength="60" value="${h(u.team)}" list="teams"><datalist id="teams">${['Sistemas','Hidrología','SAD','Operadores','SAICA'].map(t=>`<option>${t}</option>`).join('')}</datalist></label><label class="field wide">Correo electrónico${ONLINE?'':' (opcional en la demo)'}<input type="email" ${ONLINE?'required':''} name="email" maxlength="254" value="${h(u.email)}"></label></div><div class="stack" style="margin-top:18px">${profileFields(u)}</div><div class="error" role="alert"></div><div class="form-actions"><button type="button" class="btn" data-action="dismiss">Cancelar</button><button class="btn primary">Guardar ficha</button></div></form>`);}
function exportCsv(include){const e=current();const rows=[['comida_id','comida','fecha','hora','lugar','mapa','web_restaurante','persona_id','nombre','equipo','asistencia','voto','acompañantes','nombres_acompañantes',...(include?['alergias_intolerancias','preferencias','alimentacion_acompañantes']:[])],...e.invitations.map(i=>{const u=user(i.userId);return [e.id,e.title,e.date,e.time||'',e.place,e.mapsUrl||'',e.websiteUrl||'',u.id,u.name,u.team,{yes:'Confirmado',no:'No asiste',pending:'Pendiente'}[i.response],e.options.find(o=>o.id===i.vote)?.label||'',i.response==='yes'?(i.companions||[]).length:0,(i.companions||[]).map(g=>g.name).join(' / '),...(include?[allergy(u),u.preferences,(i.companions||[]).map(g=>g.name+': '+(g.allergies||'Sin indicar')).join(' / ')]:[])];})];const url=URL.createObjectURL(new Blob([C.csv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='comida-saih-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',async ev=>{const b=ev.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;try{
if(action==='add-invitees')addInviteesForm();
if(action==='go-users'){modal.close();page='users';render();}
if(action==='refresh'){data=await R.snapshot();render();toast('Datos actualizados.');}
if(action==='logout'){await R.logout();loginScreen();}

if(action==='review-invites'){const e=current(),recipients=e.invitations.filter(i=>selectedInvites.has(i.userId)).map(i=>user(i.userId));if(recipients.length>30){toast('Selecciona como máximo 30 personas por envío.');return;}batchRequest={eventId:e.id,userIds:recipients.map(u=>u.id),requestId:C.uid()};show('Revisar invitaciones',`<p>Se enviará un correo individual a cada persona, con su propio botón de acceso.</p><ul>${recipients.map(u=>`<li>${h(u.name)} · ${h(u.email)}</li>`).join('')}</ul><section class="notice"><strong>${h(e.title)}</strong><p>${date(e.date)} · ${h(e.time||'Hora por decidir')}<br>${h(e.place||'Lugar por decidir')}</p><p>${e.stage==='poll'?'Elige el tipo de comida que prefieres.':'Confirma si puedes asistir.'}</p><strong>${e.stage==='poll'?'Votar en la encuesta':'Confirmar asistencia'}</strong><p>El botón será personal para cada destinatario.</p></section><p>Al enviar una nueva invitación, su enlace anterior para esta comida se sustituirá.</p>${R.emailEnabled?'':'<p class="notice warn">Falta conectar la cuenta remitente para activar el envío automático.</p>'}<div class="error" role="alert"></div><div class="form-actions"><button class="btn" data-action="dismiss">Volver</button><button class="btn primary" data-action="send-invites" ${R.emailEnabled?'':'disabled'}>Enviar ${recipients.length} invitaciones</button></div>`);}
if(action==='send-invites')await sendBatch(b);
if(action==='personal-invite'){show('Invitación personal',`<p>Se generará un enlace para <strong>${h(user(id).name)}</strong>. Si ya tenía un enlace anterior para esta comida, dejará de funcionar.</p><p>El enlace permite responder y editar su ficha alimentaria. Envíalo únicamente a esta persona.</p><div class="form-actions"><button class="btn" data-action="dismiss">Cancelar</button><button class="btn primary" data-action="generate-invite" data-id="${h(id)}">Generar enlace</button></div>`);}
if(action==='generate-invite'){const link=await R.invitation(eventId,id),e=current(),u=user(id);const text=`Hola ${u.name}:\n\n${e.title}\nFecha: ${date(e.date)}\nHora: ${e.time||'Por decidir'}\nLugar: ${e.place||'Por decidir'}\n${e.mapsUrl?'Mapa: '+e.mapsUrl+'\n':''}${e.websiteUrl?'Web: '+e.websiteUrl+'\n':''}\n${e.stage==='poll'?'Vota el tipo de comida que prefieres.':'Confirma si puedes asistir.'}\n${link}\n\nEste enlace es personal. No lo reenvíes.`;show('Invitación preparada',`<p>Destinatario: ${h(u.email)}</p><textarea id="invite-text" rows="12" readonly aria-label="Texto de invitación">${h(text)}</textarea><div class="form-actions"><button class="btn" data-action="copy-invite">Copiar texto</button><a class="btn primary" href="mailto:${encodeURIComponent(u.email)}?subject=${encodeURIComponent(e.title)}&body=${encodeURIComponent(text)}">Abrir en mi correo</a></div>`);}
if(action==='nav'){page=id;if(role==='guest'&&id==='users'){page='meals';toast('En la vista de invitado solo se muestra la ficha personal.');}render();}
if(action==='role'){role=id;page='meals';render();}
if(action==='dismiss')modal.close();
if(action==='new-event')eventForm();if(action==='edit-event')eventForm(true);
if(action==='new-user')userForm();if(action==='edit-user')userForm(id);
if(action==='simulate'){role='guest';guestId=id;page='meals';render();}
if(action==='finish-poll'){const food=document.getElementById('chosen-food').value;await commit(d=>{const e=d.events.find(e=>e.id===eventId);C.ready(e);e.stage='confirm';e.food=food;e.deadline='';});render();toast('Confirmación abierta. Puedes fijar un nuevo plazo en Editar detalles.');}
if(action==='close-event')show('Cerrar respuestas',`<p>Se conservarán todos los votos y respuestas. Los invitados ya no podrán cambiarlos.</p><div class="form-actions"><button class="btn" data-action="dismiss">Cancelar</button><button class="btn primary" data-action="confirm-close">Cerrar comida</button></div>`);
if(action==='confirm-close'||action==='reopen'){await commit(d=>{const e=d.events.find(e=>e.id===eventId);if(action==='reopen')C.ready(e);e.stage=action==='reopen'?'confirm':'closed';if(action==='reopen')e.deadline='';});modal.close();render();toast(action==='reopen'?'Confirmación reabierta sin fecha límite.':'Comida cerrada.');}
if(action==='export')show('Exportar listado',`<p>Descarga las respuestas de esta comida como CSV, compatible con Excel.</p><label class="inline"><input id="include-allergies" type="checkbox">Incluir alergias, intolerancias y preferencias</label><div class="form-actions"><button class="btn primary" data-action="download">Descargar CSV</button></div>`);
if(action==='download'){exportCsv(document.getElementById('include-allergies').checked);modal.close();}
if(action==='invitation'){const e=current();const text=`Hola:\n\nEstamos organizando ${e.title}.\nFecha: ${date(e.date)}.\nHora: ${e.time||'Por decidir'}.\nLugar: ${e.place||'Por decidir'}.\n${e.mapsUrl?'Mapa: '+e.mapsUrl+'\n':''}${e.websiteUrl?'Restaurante: '+e.websiteUrl+'\n':''}\n\n${e.stage==='poll'?'Vota el tipo de comida que prefieres.':'Confirma si vas a asistir.'} ${e.deadline?'Responde antes del '+date(e.deadline)+'.':''}\n\n[ENLACE PERSONAL: DISPONIBLE AL CONECTAR LA WEB]\n\nPuedes indicar tus alergias, intolerancias y preferencias alimentarias en tu ficha.\n\n¡Gracias!`;show('Texto para el correo',`<p class="notice warn">Borrador de prueba. Aún no genera enlaces personales ni envía correos.</p><textarea id="invite-text" rows="13" readonly aria-label="Texto de invitación">${h(text)}</textarea><div class="form-actions"><button class="btn primary" data-action="copy-invite">Copiar texto</button></div>`);}
if(action==='copy-invite'){const t=document.getElementById('invite-text');navigator.clipboard?.writeText(t.value).then(()=>toast('Texto copiado.')).catch(()=>{t.select();toast('Seleccionado: usa Ctrl+C para copiar.');});if(!navigator.clipboard){t.select();toast('Seleccionado: usa Ctrl+C para copiar.');}}
if(action==='reset')show('Restablecer la demo',`<p>Se borrarán únicamente las comidas y usuarios de esta demostración guardados en este navegador.</p><div class="form-actions"><button class="btn" data-action="dismiss">Cancelar</button><button class="btn danger" data-action="confirm-reset">Restablecer</button></div>`);
if(action==='confirm-reset'){const next=C.seed();localStorage.setItem(KEY,JSON.stringify(next));data=next;eventId=next.events[0].id;guestId=next.users[0].id;storageOk=true;modal.close();render();toast('Demo restablecida.');}
}catch(err){toast(R.errorMessage(err));}});
document.addEventListener('change',ev=>{const el=ev.target,kind=el.dataset.change;if(el.name==='answer'){const section=document.getElementById('companion-section');if(section){section.hidden=el.value!=='yes';section.disabled=el.value!=='yes';}}if(kind==='companions'){document.querySelectorAll('[data-companion]').forEach((box,n)=>{box.hidden=n>=Number(el.value);box.disabled=box.hidden;});}if(kind==='invite-one'){el.checked?selectedInvites.add(el.dataset.id):selectedInvites.delete(el.dataset.id);render();}if(kind==='invite-all'){current().invitations.filter(i=>filter==='all'||i.response===filter).forEach(i=>el.checked?selectedInvites.add(i.userId):selectedInvites.delete(i.userId));render();}if(kind==='event'){selectedInvites.clear();eventId=el.value;filter='all';render();}if(kind==='guest'){guestId=el.value;render();}if(kind==='filter'){filter=el.value;render();}if(kind==='allergy'){const box=el.closest('form').querySelector('.allergy-detail');box.hidden=el.value!=='specified';box.querySelector('textarea').required=el.value==='specified';}if(kind==='stage')el.closest('form').querySelector('.poll-options').hidden=el.value!=='poll';});
document.addEventListener('submit',async ev=>{ev.preventDefault();const form=ev.target,fd=Object.fromEntries(new FormData(form)),err=form.querySelector('.error');if(form.dataset.busy)return;form.dataset.busy='1';const submit=form.querySelector('button:not([type=button])');if(submit)submit.disabled=true;try{
if(form.id==='add-invitees-form'){const ids=new FormData(form).getAll('invitee');if(!ids.length)throw Error('Selecciona al menos una persona.');if(ids.length>30)throw Error('Selecciona entre 1 y 30 invitados por envío.');if(ONLINE){if(!R.emailEnabled)throw Error('Falta conectar la cuenta de correo para activar el envío automático.');data=await R.addInvitees(form.dataset.event,ids);}else{const next=structuredClone(data),e=next.events.find(e=>e.id===form.dataset.event);if(e.stage==='closed'||C.isExpired(e))throw Error('Reabre la comida o amplía el plazo antes de añadir personas.');for(const id of ids)if(!e.invitations.some(i=>i.userId===id))e.invitations.push({userId:id,response:'pending',vote:null,companions:[]});localStorage.setItem(KEY,JSON.stringify(next));data=next;}selectedInvites.clear();ids.forEach(id=>selectedInvites.add(id));filter='all';modal.close();render();if(ONLINE){batchRequest={eventId:form.dataset.event,userIds:ids,requestId:C.uid()};show('Enviando invitaciones',`<p>Las personas ya están añadidas. Enviando ${ids.length} correos individuales…</p><div class="error" role="alert"></div><button class="btn primary" data-action="send-invites" disabled>Reintentar este lote</button>`);await sendBatch(modal.querySelector('[data-action=send-invites]'));}else toast('Personas añadidas a la demo.');}
if(form.id==='login-form'){await R.login(fd.email.trim());form.innerHTML='<div class="notice">Si tu cuenta está autorizada, recibirás un enlace para acceder. Revisa también el correo no deseado.</div>';return;}
if(form.id==='event-form'){if(!fd.title.trim())throw Error('Escribe el nombre de la comida.');if(fd.date&&fd.deadline&&fd.deadline>fd.date)throw Error('El plazo de respuesta no puede ser posterior a la comida.');let selected=eventId;await commit(d=>{if(form.dataset.edit){const event=d.events.find(e=>e.id===eventId);const change=event.date!==fd.date||(event.time||'')!==fd.time||event.place!==fd.place.trim();const updated={...event,title:fd.title.trim(),date:fd.date,time:fd.time,place:fd.place.trim(),deadline:fd.deadline,food:fd.food.trim(),mapsUrl:C.safeUrl(fd.mapsUrl),websiteUrl:C.safeUrl(fd.websiteUrl)};if(updated.stage==='confirm')C.ready(updated);Object.assign(event,updated);if(change)event.invitations.forEach(i=>i.response='pending');}else{let options=fd.stage==='poll'?fd.options.split('\n').map(x=>x.trim()).filter(Boolean):[];if(fd.stage==='poll'&&(options.length<2||options.length>8))throw Error('La encuesta necesita entre 2 y 8 opciones.');if(new Set(options.map(x=>x.toLowerCase())).size!==options.length)throw Error('Hay opciones repetidas.');if(options.some(o=>o.length>100))throw Error('Cada opción puede tener hasta 100 caracteres.');if(!d.users.length)throw Error('Añade al menos una persona antes de crear la comida.');if(fd.stage==='confirm')C.ready(fd);selected=C.uid();d.events.unshift({id:selected,title:fd.title.trim(),date:fd.date,time:fd.time,mapsUrl:C.safeUrl(fd.mapsUrl),websiteUrl:C.safeUrl(fd.websiteUrl),place:fd.place.trim(),deadline:fd.deadline,stage:fd.stage,food:fd.food.trim(),options:options.map(label=>({id:C.uid(),label})),invitations:d.users.map(u=>({userId:u.id,response:'pending',vote:null}))});}});eventId=selected;filter='all';modal.close();render();toast('Comida guardada.');}
if(form.id==='user-form'){if(!fd.name.trim()||!fd.team.trim())throw Error('Completa nombre y equipo.');await commit(d=>{if(fd.email&&d.users.some(u=>u.id!==form.dataset.id&&u.email.toLowerCase()===fd.email.trim().toLowerCase()))throw Error('Ya existe una persona con ese correo.');let u=d.users.find(u=>u.id===form.dataset.id);if(!u){u={id:C.uid()};d.users.push(u);}Object.assign(u,{name:fd.name.trim(),team:fd.team.trim(),email:fd.email.trim().toLowerCase()});C.profile(u,fd);});modal.close();render();toast('Ficha guardada.');}
if(form.id==='profile-form'){await commit(d=>C.profile(d.users.find(u=>u.id===guestId),fd));render();toast('Tu ficha se ha guardado.');}
if(form.id==='reply-form'){await commit(d=>{const e=d.events.find(e=>e.id===eventId);if(e.stage==='poll')C.vote(e,guestId,fd.answer);else C.respond(e,guestId,fd.answer,Array.from({length:fd.answer==='yes'?Number(fd.companionCount||0):0},(_,n)=>({name:fd['companionName'+n],allergies:fd['companionAllergies'+n]})));});if(current().stage==='poll'){render();toast('Voto guardado.');}else thankYou();}
}catch(error){if(err)err.textContent=R.errorMessage(error);else toast(R.errorMessage(error));}finally{delete form.dataset.busy;if(submit)submit.disabled=false;}});
function thankYou(){
 const e=current(),i=e.invitations.find(i=>i.userId===guestId);
 const label={yes:'Sí, voy',no:'No puedo ir',pending:'Todavía no lo sé'}[i.response];
 app.innerHTML=`<main class="thanks-page"><section class="thanks-card" aria-labelledby="thanks-title"><img class="thanks-logo" src="logo-saih.webp" alt="SAIH Tajo · Comidas" width="1370" height="1148"><span class="thanks-check" aria-hidden="true">✓</span><p class="eyebrow">RESPUESTA GUARDADA</p><h1 id="thanks-title" tabindex="-1">¡Gracias por confirmar<br>tu disponibilidad!</h1><p class="thanks-copy">Richard ya puede consultar tu respuesta.</p><div class="thanks-summary"><strong>${h(e.title)}</strong><span>${h(date(e.date))}${e.time?' · '+h(e.time):''}</span>${(i.companions||[]).length?`<span>Acompañantes: ${(i.companions||[]).map(g=>h(g.name)).join(', ')}</span>`:''}<span class="pill ${i.response==='yes'?'green':i.response==='no'?'red':'amber'}">${h(label)}</span></div><p class="thanks-close">Ya puedes cerrar esta pestaña.</p><p class="muted">Si cambias de planes, vuelve a abrir tu enlace personal dentro del plazo.</p><button class="thanks-edit" id="review-response" type="button">Revisar mi respuesta o mi ficha alimentaria</button></section><p class="thanks-signature">COMIDAS · SAIH TAJO</p></main>`;
 document.getElementById('review-response').addEventListener('click',()=>render());
 document.getElementById('thanks-title').focus({preventScroll:true});window.scrollTo(0,0);
}
function loginScreen(message=''){app.innerHTML=`<main class="guest"><img class="login-logo" src="logo-saih.webp" alt="SAIH Tajo · Comidas" width="1370" height="1148"><h1>Acceso para el evento</h1><section class="panel"><div class="panel-body"><p>Entra con el correo autorizado. Te enviaremos un enlace de acceso.</p><form id="login-form"><label class="field">Correo<input type="email" name="email" required autocomplete="email"></label><div class="error" role="alert">${h(message)}</div><div class="form-actions"><button class="btn primary">Recibir enlace</button></div></form></div></section><p class="muted">Si eres invitado, abre el enlace personal que te haya enviado Richard.</p></main>`;}
async function start(){if(!ONLINE){render();return;}app.innerHTML='<main><p>Conectando…</p></main>';try{const state=await R.initialize();if(state.role==='login'){loginScreen();return;}data=state.data;role=state.role;eventId=data.events[0]?.id;guestId=data.users[0]?.id;render();}catch(error){loginScreen(R.errorMessage(error));}}
start();


